<a href="https://colab.research.google.com/github/RojaCM/Complete-Python-3-Bootcamp/blob/master/DEX%20data%20conv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
data=pd.read_json('Contents.json')

In [3]:
data

,took,timed_out,_shards,hits
total,25,False,1.0,"{'value': 2139, 'relation': 'eq'}"
successful,25,False,1.0,NaN
skipped,25,False,0.0,NaN
failed,25,False,0.0,NaN
max_score,25,False,NaN,1.0
hits,25,False,NaN,"[{'_index': 'contents', '_id': '6349491dc4dbd3..."

In [19]:
df=data.loc['hits']['hits']

In [20]:
type(df)

list

In [21]:
df1=pd.json_normalize(df)

In [22]:
df1

,_index,_id,_score,_source.@version,_source.document.updated_by,_source.document.title,_source.document.createdAt,_source.document.__v,_source.document.readCount,_source.document.createdDate,...,_source.document.authorId,_source.document.summary,_source.document.likesCount,_source.document.type,_source.document.createdBy,_source.document.updatedAt,_source.document.created_by,_source.@timestamp,_ignored,_source.document.authorName
0,contents,6349491dc4dbd32b83faac95,1.0,1,None,Reminder - Optimus - Best People Manager 2022,2022-10-14T11:33:49.068Z,0,0.0,2022-10-14T11:33:49.048Z,...,DEX001,Today is the last day for voting (14th October...,0.0,TWEETS,AIPL14906,2022-10-14T11:33:49.068Z,None,2022-10-14T11:34:00.515993395Z,NaN,NaN
1,contents,634947d2c4dbd32b83faac8e,1.0,1,None,"It starts this 23 October, till 26 October 202...",2022-10-14T11:28:18.718Z,0,0.0,2022-10-14T11:28:18.704Z,...,rangak,Hope you are all set to attend Money 2020 USA ...,0.0,TWEETS,AIPL14906,2022-10-14T11:28:18.718Z,None,2022-10-14T11:28:30.468189346Z,NaN,NaN
2,contents,6349464cc4dbd32b83faac7c,1.0,1,None,Congratulations Triveni Arun Bhalerao | Long S...,2022-10-14T11:21:48.370Z,0,0.0,2022-10-14T11:21:48.356Z,...,krishnam,,0.0,WHO_SAID_WHAT,AIPL14906,2022-10-14T11:21:48.370Z,None,2022-10-14T11:22:00.385534530Z,NaN,NaN
3,contents,634942e7c4dbd32b83faac68,1.0,1,None,Long Service Awards - 5 years - Triveni Arun ...,2022-10-14T11:07:19.878Z,0,0.0,2022-10-14T11:07:19.853Z,...,krishnam,,0.0,STORY_OF_THE_DAY,AIPL14906,2022-10-14T11:07:19.878Z,None,2022-10-14T11:07:30.231646957Z,NaN,NaN
4,contents,6329754d8d07853a3016f6a9,1.0,1,None,tweets testing,2022-09-20T08:09:49.036Z,0,0.0,2022-09-20T08:09:49.023Z,...,AIPL13982,today testing preview screen and toast success...,0.0,TWEETS,AIPL13982,2022-10-14T10:57:22.572Z,None,2022-10-14T10:57:30.125637363Z,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,contents,627e219f3ab56f0f0ebe708f,1.0,1,601d820e0d680057ffd35a55,"Employee Referral Virtual Drive - 14 May, 2022",2022-05-13T09:15:11.822Z,0,NaN,2022-05-13T06:30:00.000Z,...,DEX001,,0.0,COMPANY_INFORMATION,AIPL14906,2022-05-13T09:15:13.678Z,601d820e0d680057ffd35a55,2022-09-28T10:56:17.514358467Z,NaN,NaN
996,contents,627e27163ab56f0f0ebe70ac,1.0,1,601d820e0d680057ffd35a55,The Future Trends In Mobility And Transportation,2022-05-13T09:38:30.050Z,0,NaN,2022-05-13T06:30:00.000Z,...,DEX001,,0.0,INDUSTRY_UPDATE,AIPL14906,2022-05-13T09:59:37.142Z,601d820e0d680057ffd35a55,2022-09-28T10:56:17.514462430Z,NaN,NaN
997,contents,627e2b163ab56f0f0ebe70b5,1.0,1,601d820e0d680057ffd35a55,The Keys to Pricing Power as Recession Looms,2022-05-13T09:55:34.255Z,0,NaN,2022-05-13T06:30:00.000Z,...,DEX001,,0.0,INDUSTRY_UPDATE,AIPL14906,2022-05-13T09:57:08.604Z,601d820e0d680057ffd35a55,2022-09-28T10:56:17.514567962Z,NaN,NaN
998,contents,627e30583ab56f0f0ebe70ba,1.0,1,601d820e0d680057ffd35a55,Intelligence and unified data governance in th...,2022-05-13T10:18:00.993Z,0,NaN,2022-05-13T06:30:00.000Z,...,DEX001,,0.0,TECHNO_PICKS,AIPL14906,2022-05-13T10:18:03.858Z,601d820e0d680057ffd35a55,2022-09-28T10:56:17.514675116Z,NaN,NaN
999,contents,627e32943ab56f0f0ebe70bf,1.0,1,601d820e0d680057ffd35a55,Creating a defined data centric space with AI ...,2022-05-13T10:27:32.389Z,0,NaN,2022-05-13T06:30:00.000Z,...,DEX001,,0.0,TECHNO_PICKS,AIPL14906,2022-05-13T10:27:36.454Z,601d820e0d680057ffd35a55,2022-09-28T10:56:17.514779960Z,NaN,NaN

In [24]:
cols=['_source.document.title','_source.document.summary','_source.document.type']

In [25]:
data1=df1[cols]

In [26]:
data1

,_source.document.title,_source.document.summary,_source.document.type
0,Reminder - Optimus - Best People Manager 2022,Today is the last day for voting (14th October...,TWEETS
1,"It starts this 23 October, till 26 October 202...",Hope you are all set to attend Money 2020 USA ...,TWEETS
2,Congratulations Triveni Arun Bhalerao | Long S...,,WHO_SAID_WHAT
3,Long Service Awards - 5 years - Triveni Arun ...,,STORY_OF_THE_DAY
4,tweets testing,today testing preview screen and toast success...,TWEETS
...,...,...,...
995,"Employee Referral Virtual Drive - 14 May, 2022",,COMPANY_INFORMATION
996,The Future Trends In Mobility And Transportation,,INDUSTRY_UPDATE
997,The Keys to Pricing Power as Recession Looms,,INDUSTRY_UPDATE
998,Intelligence and unified data governance in th...,,TECHNO_PICKS
999,Creating a defined data centric space with AI ...,,TECHNO_PICKS

In [27]:
data1.rename(columns={'_source.document.title':'title','_source.document.summary':'summary','_source.document.type':'category'},inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:5047: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [28]:
data1

,title,summary,category
0,Reminder - Optimus - Best People Manager 2022,Today is the last day for voting (14th October...,TWEETS
1,"It starts this 23 October, till 26 October 202...",Hope you are all set to attend Money 2020 USA ...,TWEETS
2,Congratulations Triveni Arun Bhalerao | Long S...,,WHO_SAID_WHAT
3,Long Service Awards - 5 years - Triveni Arun ...,,STORY_OF_THE_DAY
4,tweets testing,today testing preview screen and toast success...,TWEETS
...,...,...,...
995,"Employee Referral Virtual Drive - 14 May, 2022",,COMPANY_INFORMATION
996,The Future Trends In Mobility And Transportation,,INDUSTRY_UPDATE
997,The Keys to Pricing Power as Recession Looms,,INDUSTRY_UPDATE
998,Intelligence and unified data governance in th...,,TECHNO_PICKS
999,Creating a defined data centric space with AI ...,,TECHNO_PICKS

In [29]:
data1.to_csv('sample_dex_data.csv')